# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: atelier NZML 
name: atelierNZML 
email: hogehoge@example.com
repository: atelierNZML/atelier-nzml.github.io 

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# url: http://localhost:4000
url: https://ateliernzml.github.io

## Gem
# gems:
#   - jekyll-paginate
#   - jekyll-paginate-multiple
#   - jekyll-geo-pattern
#   - rouge
#   - kramdown
#   - jekyll-github-metadata

# Build settings
# markdown: kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

# kramdown:
#   input: GFM
#   enable_coderay: true

# Disque
# disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
# paginate: 10
# paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /about
    label: About
    icon: <i class="fa-regular fa-user-circle"></i>
  -
    href: /nazoml
    label: 謎解き
    icon: <i class="fa-regular fa-circle-question"></i>
  -
    href: /minecraft
    label: Minecraft
    icon: <i class="fa-solid fa-gamepad"></i>
  -
    href: /nzmlynx
    label: その他活動
    icon: <i class="fa-solid fa-globe"></i>


# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

